name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "SOP"
    labels: ["sop"]
  - title: "Docs"
    labels: ["documentation"]
  - title: "Repo"
    labels: ["chore"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes
  $CHANGES
